<?php

return [
    'web.modules' => [
        'name' => 'Modules',
        'route' => 'lawoo.modules',
        'middleware' => 'super-admin',
        'level' => 0,
        'icon' => 'squares-plus',
        'sort_order' => 9900,
        'group' => null,
    ],
    'web.modules.records' => [
        'parent' => 'web.modules',
        'name' => 'Modules',
        'route' => 'lawoo.modules',
        'middleware' => 'super-admin',
        'level' => 1,
        'icon' => null,
        'sort_order' => 100,
        'group' => null,
    ],
    'web.modules.check' => [
        'parent' => 'web.modules',
        'name' => 'Check',
        'route' => 'lawoo.modules.check',
        'middleware' => 'super-admin',
        'level' => 1,
        'icon' => null,
        'sort_order' => 200,
        'group' => null,
    ],
    'web.settings' => [
        'name' => 'Settings',
        'route' => 'lawoo.settings.index',
        'middleware' => 'web.settings.show',
        'level' => 0,
        'icon' => 'cog',
        'sort_order' => 10000,
        'group' => null
    ],
    'web.settings.view' => [
        'parent' => 'web.settings',
        'name' => 'Settings',
        'route' => 'lawoo.settings.index',
        'middleware' => 'web.settings.show',
        'level' => 1,
        'icon' => null,
        'sort_order' => 100,
    ],
    'web.settings.roles_permissions' => [
        'parent' => 'web.settings',
        'name' => 'Roles Permissions',
        'route' => false,
        'middleware' => 'web.settings.roles_permissions.show',
        'level' => 1,
        'icon' => null,
        'sort_order' => 200,
    ],
    'web.settings.roles' => [
        'parent' => 'web.settings.roles_permissions',
        'name' => 'Roles',
        'route' => 'lawoo.settings.roles.records',
        'middleware' => 'web.settings.roles_permissions.show',
        'level' => 2,
        'icon' => null,
        'sort_order' => 100
    ],
    'web.settings.companies' => [
        'parent' => 'web.settings',
        'name' => 'Companies',
        'route' => 'lawoo.settings.companies.records',
        'middleware' => 'web.settings.companies.show',
        'level' => 1,
        'icon' => null,
        'sort_order' => 300,
    ],
    'web.settings.country_language' => [
        'parent' => 'web.settings',
        'name' => 'Countries & Languages',
        'route' => false,
        'middleware' => 'web.settings.country_language.show',
        'level' => 1,
        'icon' => null,
        'sort_order' => 400,
    ],
    'web.settings.country' => [
        'parent' => 'web.settings.country_language',
        'name' => 'Countries',
        'route' => 'lawoo.settings.countries',
        'middleware' => 'web.settings.country_language.show',
        'level' => 2,
        'icon' => null,
        'sort_order' => 100,
    ],
    'web.settings.language' => [
        'parent' => 'web.settings.country_language',
        'name' => 'Languages',
        'route' => 'lawoo.settings.languages',
        'middleware' => 'web.settings.country_language.show',
        'level' => 2,
        'icon' => null,
        'sort_order' => 200,
    ],
    'web.settings.translations' => [
        'parent' => 'web.settings.country_language',
        'name' => 'Translations',
        'route' => 'lawoo.settings.translations',
        'middleware' => 'web.settings.country_language.show',
        'level' => 2,
        'icon' => null,
        'sort_order' => 300,
    ]
];
