settings:
  base: 1
  sequence: 10
  fields:
    id: id
    value: string.nullable
    settings_menu_id: foreignId.constrained.onDelete=cascade
    key: string.unique.index
    module_name: string=100.nullable
    created_at: timestamp.nullable
    updated_at: timestamp.nullable
