user_settings:
  base: 1
  sequence: 10
  fields:
    id: id
    name: string=100
    data: json
    user_id: integer.nullable
    key: string=256.index
    default: boolean.default=0
    public: boolean.default=0.index
    is_active: boolean.default=1.index
    sequence: integer.default=10
    created_at: timestamp.useCurrent
    updated_at: timestamp.nullable
