<?php

namespace Modules\Website\Http\Livewire\Form;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Modules\Web\Http\Livewire\Form\BaseFormView;
use Modules\Website\Models\Theme;
use Modules\Website\Repositories\AssetRepository;
use Modules\Website\Repositories\WebsiteRepository;
use Modules\Website\Services\ContentManager;

class AssetFormView extends BaseFormView
{
    /**
     * !Required
     * @var string
     */
    protected string $repositoryClass = AssetRepository::class;

    /**
     * !Required
     * @var string
     */
    public string $recordsRoute = 'lawoo.website.assets.records';

    /**
     * !Required only by Create type
     * @var string
     */
    public string $recordRoute = 'lawoo.website.assets.records.view';

    /**
     * Only by TrackableModel
     * @var bool
     */
    public bool $showMessages = false;

    protected function loadData(): void
    {
        parent::loadData(); // TODO: Change the autogenerated stub
        if ($this->record) {
            $this->fields['content']['languages'] = $this->record->type;
        }
    }

    /**
     * Set Fields function
     */
    public function setFields(): void
    {
        $this->fields = [
            'name' => [
                'label' => __t('Name', 'Web'),
                'type' => 'input',
                'class' => 'lg:col-span-6',
                'required' => true,
            ],
            'path' => [
                'label' => __t('Path', 'Website'),
                'type' => 'input',
                'class' => 'lg:col-span-4',
                'disabled' => true,
            ],
            'type' => [
                'label' => __t('Type', 'Website'),
                'type' => 'select',
                'class' => 'lg:col-span-2',
                'options' => [
                    'css' => 'CSS',
                    'scss' => 'SCSS',
                    'js' => 'JavaScript',
                    'svg' => 'SVG',
                ],
                'change' => 'changeType',
                'disabled' => !($this->type === 'create'),
            ],
            'internal_note' => [
                'label' => __t('Internal Note', 'Website'),
                'type' => 'textarea',
                'class' => 'lg:col-span-12',
            ],
            'content' => [
                'label' => __t('Content', 'Website'),
                'type' => 'editor',
                'mode' => 'code',
                'languages' => '',
                'class' => 'lg:col-span-12',
                'ignore' => $this->type !== 'create',
            ],
            'theme_id' => [
                'label' => __t('Theme', 'Website'),
                'type' => 'select',
                'class' => 'lg:col-span-6',
                'options' => $this->getThemes(),
            ],
            'website_id' => [
                'label' => __t('Website', 'Website'),
                'type' => 'select',
                'class' => 'lg:col-span-6',
                'options' => $this->getWebsites(),
            ],
            'company_id' => [
                'label' => __t('Company', 'Website'),
                'type' => 'select',
                'class' => 'lg:col-span-6',
                'options' => self::getCompanies(),
            ],
            'is_active' => [
                'label' => __t('Active', 'Website'),
                'type' => 'switch',
                'class' => 'lg:col-span-3',
                'default' => true,
            ],
            'auto_public' => [
                'label' => __t('Publish automatically', 'Website'),
                'type' => 'switch',
                'class' => 'lg:col-span-3',
                'default' => false,
            ],
            'is_public' => [
                'label' => __t('Public', 'Website'),
                'type' => 'hidden',
                'class' => 'lg:col-span-6',
                'default' => false,
            ],
            'is_changed' => [
                'label' => __t('Changed', 'Website'),
                'type' => 'hidden',
                'class' => 'lg:col-span-6',
                'default' => false,
            ],
        ];
    }

    public function changeType(): void
    {
        $this->fields['content']['languages'] = $this->data['type'] ?? '';
        $this->dispatch('render-code-editor');
    }

    public function getThemes(): array
    {
        return Theme::all()->pluck('name', 'id')->toArray();
    }

    protected function getWebsites(): array
    {
        $websiteRepository = new WebsiteRepository();
        return $websiteRepository->getFilteredData()->pluck('name', 'id')->toArray();
    }

    public function setRules(): void
    {
        $this->rules = [
            'data.name' => 'required|min:3|max:150',
        ];
    }

    protected function extraHeaderView(): string
    {
        return 'livewire.website.form.asset-extra-header-view';
    }

    public function publish(): void
    {
        ContentManager::publish($this->record);
        $this->data['is_public'] = true;
        $this->data['is_changed'] = false;
        if (!$this->data['path']) $this->data['path'] = Str::slug($this->record->name);
        $this->update();
    }

    public function unpublish(): void
    {
        ContentManager::unpublish($this->record);
        $this->data['is_public'] = false;
        $this->data['is_changed'] = false;
        if ($this->data['path']) $this->data['path'] = '';
        $this->update();
    }

    public function updated($property, $value): void
    {
        if ($property === 'data.is_active' && $value === false) {
            self::unpublish();
        }
    }

    protected function update(): ?Model
    {
        $update = parent::update();
        $this->dispatch('reload-form-data');
        return $update;
    }
}
